require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Id3TagsController do

  # This should return the minimal set of attributes required to create a valid
  # Id3Tag. As you add validations to Id3Tag, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "song_title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Id3TagsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all id3_tags as @id3_tags" do
      id3_tag = Id3Tag.create! valid_attributes
      get :index, {}, valid_session
      assigns(:id3_tags).should eq([id3_tag])
    end
  end

  describe "GET show" do
    it "assigns the requested id3_tag as @id3_tag" do
      id3_tag = Id3Tag.create! valid_attributes
      get :show, {:id => id3_tag.to_param}, valid_session
      assigns(:id3_tag).should eq(id3_tag)
    end
  end

  describe "GET new" do
    it "assigns a new id3_tag as @id3_tag" do
      get :new, {}, valid_session
      assigns(:id3_tag).should be_a_new(Id3Tag)
    end
  end

  describe "GET edit" do
    it "assigns the requested id3_tag as @id3_tag" do
      id3_tag = Id3Tag.create! valid_attributes
      get :edit, {:id => id3_tag.to_param}, valid_session
      assigns(:id3_tag).should eq(id3_tag)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Id3Tag" do
        expect {
          post :create, {:id3_tag => valid_attributes}, valid_session
        }.to change(Id3Tag, :count).by(1)
      end

      it "assigns a newly created id3_tag as @id3_tag" do
        post :create, {:id3_tag => valid_attributes}, valid_session
        assigns(:id3_tag).should be_a(Id3Tag)
        assigns(:id3_tag).should be_persisted
      end

      it "redirects to the created id3_tag" do
        post :create, {:id3_tag => valid_attributes}, valid_session
        response.should redirect_to(Id3Tag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved id3_tag as @id3_tag" do
        # Trigger the behavior that occurs when invalid params are submitted
        Id3Tag.any_instance.stub(:save).and_return(false)
        post :create, {:id3_tag => { "song_title" => "invalid value" }}, valid_session
        assigns(:id3_tag).should be_a_new(Id3Tag)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Id3Tag.any_instance.stub(:save).and_return(false)
        post :create, {:id3_tag => { "song_title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested id3_tag" do
        id3_tag = Id3Tag.create! valid_attributes
        # Assuming there are no other id3_tags in the database, this
        # specifies that the Id3Tag created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Id3Tag.any_instance.should_receive(:update).with({ "song_title" => "MyString" })
        put :update, {:id => id3_tag.to_param, :id3_tag => { "song_title" => "MyString" }}, valid_session
      end

      it "assigns the requested id3_tag as @id3_tag" do
        id3_tag = Id3Tag.create! valid_attributes
        put :update, {:id => id3_tag.to_param, :id3_tag => valid_attributes}, valid_session
        assigns(:id3_tag).should eq(id3_tag)
      end

      it "redirects to the id3_tag" do
        id3_tag = Id3Tag.create! valid_attributes
        put :update, {:id => id3_tag.to_param, :id3_tag => valid_attributes}, valid_session
        response.should redirect_to(id3_tag)
      end
    end

    describe "with invalid params" do
      it "assigns the id3_tag as @id3_tag" do
        id3_tag = Id3Tag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Id3Tag.any_instance.stub(:save).and_return(false)
        put :update, {:id => id3_tag.to_param, :id3_tag => { "song_title" => "invalid value" }}, valid_session
        assigns(:id3_tag).should eq(id3_tag)
      end

      it "re-renders the 'edit' template" do
        id3_tag = Id3Tag.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Id3Tag.any_instance.stub(:save).and_return(false)
        put :update, {:id => id3_tag.to_param, :id3_tag => { "song_title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested id3_tag" do
      id3_tag = Id3Tag.create! valid_attributes
      expect {
        delete :destroy, {:id => id3_tag.to_param}, valid_session
      }.to change(Id3Tag, :count).by(-1)
    end

    it "redirects to the id3_tags list" do
      id3_tag = Id3Tag.create! valid_attributes
      delete :destroy, {:id => id3_tag.to_param}, valid_session
      response.should redirect_to(id3_tags_url)
    end
  end

end
